# Generated by Django 4.2.7 on 2025-12-10 14:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BounceEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('uploaded_by_user_id', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'bounce_emails',
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('file_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('uploaded_by_user_id', models.CharField(max_length=50)),
                ('original_record_count', models.IntegerField(default=0)),
                ('unique_record_count', models.IntegerField(default=0)),
                ('filtered_unsub_count', models.IntegerField(default=0)),
                ('filtered_bounce_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed')], default='UPLOADED', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'file_uploads',
            },
        ),
        migrations.CreateModel(
            name='VerificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('syntax_status', models.BooleanField(default=False)),
                ('domain_status', models.BooleanField(default=False)),
                ('smtp_status', models.BooleanField(default=False)),
                ('disposable_status', models.BooleanField(default=False)),
                ('catch_all_status', models.BooleanField(default=False)),
                ('role_based_status', models.BooleanField(default=False)),
                ('final_status', models.CharField(choices=[('VALID', 'Valid'), ('INVALID', 'Invalid'), ('RISKY', 'Risky'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('verified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='files.fileupload')),
            ],
            options={
                'db_table': 'verification_results',
                'indexes': [models.Index(fields=['file', 'email'], name='verificatio_file_id_487466_idx')],
            },
        ),
    ]
