# Generated by Django 4.2.7 on 2026-01-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='invalid_record_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unsubscribedemail',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
    ]
