# Generated by Django 4.2.7 on 2026-02-08 19:02

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_fileupload_invalid_record_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='processed_records',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='total_records',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileupload',
            name='valid_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
